.SFDCFormField
{ 
  FONT-FAMILY: Arial, Verdana, Helvetica;
  FONT-WEIGHT: normal;
  COLOR: #000000;
  FONT-SIZE: 12px;
  PADDING-TOP: 1px;
  PADDING-LEFT: 2px;
  PADDING-RIGHT: 2px;
  PADDING-BOTTOM: 1px;
  WIDTH: 85%;
}

.SFDCFormFieldHalf
{ 
  FONT-FAMILY: Arial, Verdana, Helvetica;
  FONT-WEIGHT: normal;
  COLOR: #000000;
  FONT-SIZE: 12px;
  PADDING-TOP: 1px;
  PADDING-LEFT: 2px;
  PADDING-RIGHT: 2px;
  PADDING-BOTTOM: 1px;
  WIDTH: 50%;
}