<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Campaign_Invite</fullName>
        <description>Campaign Invite</description>
        <protected>false</protected>
        <recipients>
            <field>Email</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Campaigns/Campaign_Invite</template>
    </alerts>
    <alerts>
        <fullName>Registration</fullName>
        <description>Registration</description>
        <protected>false</protected>
        <recipients>
            <field>Email</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Campaigns/Campaign_Response</template>
    </alerts>
    <fieldUpdates>
        <fullName>RSVP</fullName>
        <field>Status</field>
        <literalValue>RSVP-Yes</literalValue>
        <name>RSVP</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>RSVP_Yes_True_Old</fullName>
        <field>RSVP_Yes__c</field>
        <literalValue>1</literalValue>
        <name>RSVP-Yes=True-Old</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>Campaign Invite</fullName>
        <actions>
            <name>Campaign_Invite</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>CampaignMember.Status</field>
            <operation>equals</operation>
            <value>Invited,Sent</value>
        </criteriaItems>
        <criteriaItems>
            <field>Campaign.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Campaign,Promotion</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>RSVP - Send Email</fullName>
        <actions>
            <name>Registration</name>
            <type>Alert</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>CampaignMember.Status</field>
            <operation>equals</operation>
            <value>RSVP-Yes</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>RSVP-Yes%3DTrue</fullName>
        <actions>
            <name>Registration</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>RSVP</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>CampaignMember.RSVP_Yes__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
