public class costcenter_json_controller {
    
    public String getCostcenters() {
    	return '';
    	/**
        String endpointUrl = 'https://castironpoc.w2k.nestle.net/getCostCenters';
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint(endpointUrl);
        req.setTimeout(60000);            
        //send the request
        Http http = new Http();
        HttpResponse res = http.send(req);
        return res.getBody();**/
    }

}