body{
    background-color: #444444;
    font-family: 	Arial,Verdana, sans-serif;
    font-size: 		10px;        
}

.user-panel{
	margin:			5px;
	background-color: #c0d7df;
	color:			#000000;
	-webkit-border-radius: 8px;
	-moz-border-radius: 8px;
	border-radius: 	8px;	
}

.user-panel-title-text{
	font-weight:	bold;
	font-size:		12px;
	color:			#475963;
	padding:		6px;
	padding-left:	10px;
}

.user-panel-content{
	background-color: #e3edef;
	color:			#000000;
	padding:		8px;
	padding-left:	12px;
	-webkit-border-radius: 8px;
	-moz-border-radius: 8px;
	border-radius: 	8px;
}
.user-panel-table{
	border-collapse:	collapse;
 	border-spacing: 	0px;
	padding:			0px;
	border:				0px solid #ffffff;	
}
.user-panel-table td{
	padding:			0px;
	border:				0px;
	border-collapse:	collapse;
 	border-spacing: 	0px;	
}
.rich-tab-disabled{
    background-color: #d1d1d1;
    border-color: 	#d1d1d1;
}

.category-tree-holder {
    width: 			300px;
    height: 		210px;
    overflow-x:		hidden;
    overflow-y:		scroll;        
    border: 1px solid #617d88;     
    background-color: #ffffff;   
}

.category-tree-item{
    background-color: #ffffff;
    border-bottom: 	1px solid #dddddd;
    padding: 		7px;        
    width: 			300px;
    font-weight: 	bold;
}

.pointer-cursor{
	cursor: 		pointer;    
}

.sub-category-tree-item {
    background-color: #ffffff;
    padding: 		8px;
    padding-left: 	20px;        
    border-bottom: 	1px solid #dddddd;
    width:     		300px;    
}

.defaultIndicator{
    font-weight: 	normal;
    font-size: 		8px;
    padding-left: 	4px;
}

button, input[type="submit"], input[type="reset"], input[type="button"] {
    background-color: #48c3ec;
    border: 		2px solid #ffffff;
    color: 			#FFFFFF;
    font-size: 		10px;
    font-weight: 	bold;
    margin: 		5px 3px 3px;
    padding: 		5px;
    text-decoration: none;
    text-transform: uppercase;
	-webkit-border-radius: 8px;
	-moz-border-radius: 8px;
	border-radius: 8px;

	background-image: -webkit-gradient(
	    linear,
	    left bottom,
	    left top,
	    color-stop(0.25, rgb(24,166,227)),
	    color-stop(0.86, rgb(80,195,233))
	);
	background-image: -moz-linear-gradient(
	    center bottom,
	    rgb(24,166,227) 25%,
	    rgb(80,195,233) 86%
	);
}    
.rich-tabpanel-content  {
    background-color: #ffffff;
    padding: 		0px;
    border-bottom-color: none;
    border-left-color: none;
    border-right-color: none;
    color: 			#000000;
    font-family: 	Arial,Verdana, sans-serif;
    font-size: 		10px;
    border-bottom-style: solid;
    border-bottom-width: 0px;
    border-left-style: solid;
    border-left-width: 0px;
    border-right-style: solid;
    border-right-width: 0px;
    vertical-align: top;        
}

.rich-tab-bottom-line {
    border-bottom-style: solid;
    border-bottom-width: 0px;
    border-left-style: solid;
    border-left-width: 0px;
    border-right-style: solid;
    border-right-width: 0px;    
    padding:	5px;
    padding-bottom:	7px;
    background-color:	#f3f3f3;
	background-image: -webkit-gradient(
	    linear,
    	left bottom,
    	left top,
    	color-stop(0.25, rgb(236,236,236)),
    	color-stop(0.86, rgb(252,252,252))
	);
	background-image: -moz-linear-gradient(
	    center bottom,
	    rgb(236,236,236) 25%,
	    rgb(252,252,252) 86%
	);    
}

.rich-tab-header {  
    background-image:    none;
    border-color: 	none; 
    padding: 		5px;
    text-align: 	center;
    color: 			#ffffff;
    font-family: 	Arial,Verdana,sans-serif;
    font-size: 		12px;   
    font-weight: 	bold;
    width: 			100px;
   
	-webkit-border-radius: 12px;
	-moz-border-radius: 12px;
	border-radius: 12px;    
}
    
.rich-tabhdr-side-border{
   	display: 		none;
}

.rich-tabhdr-side-cell{
    border-top-width:0px;
    border-top-style:solid;
}

.rich-tab-active {
    background-image: none;      
    background-color: #cfcfcf;
    border-color:	#b3b3b3;         
    color:    		#000000; 
    cursor: 		pointer;               
}

.rich-tab-inactive {
    background-image: none;    
    background-color: transparent;   
    border-color: 	transparent;         
    color:    		#000000; 
    cursor: 		pointer;              
}    

.activeWhite {
    background-image: none;      
    background-color: #cfcfcf;
    border-color:	#b3b3b3;         
    color:    		#000000; 
    cursor: 		pointer;               
}    

.inactiveWhite {
    background-image: none;      
    background-color: transparent;   
    border-color: 	transparent;         
    color:    		#000000; 
    cursor: 		pointer;               
}        

.bPageBlock {
	padding: 		0px;
    margin:    		0px;
    font-family: 	Arial,Verdana, sans-serif;
    font-size: 		10px;        
}

.pbHeader {
    background-color: #8caab5;

	background-image: -webkit-gradient(
	    linear,
	    left bottom,
	    left top,
	    color-stop(0.25, rgb(117,153,167)),
	    color-stop(0.82, rgb(165,188,196))
	);
	background-image: -moz-linear-gradient(
	    center bottom,
	    rgb(117,153,167) 25%,
    	rgb(165,188,196) 82%
	);
   
    height: 		40px;
}

.pbTitle {
    padding-left: 	10px;
    color: 			#ffffff;
    font-size: 		10px;
    height: 		40px;
}

.pbBody {
    color: #000000;   
    background-color: #ffffff;
    padding:		0px;
    border: 1px solid #d1d1d1;      
}    

input[type="text"], input[disabled]{
    border: 1px solid #8caab5;
    height: 		18px;
    background-color: #ffffff;
    color:			#000000;
}

.column {
	vertical-align:	top;
}
.colorTable {
	margin-left:	-5px;
}

.colorTable td {
	padding-right:	5px;
	vertical-align:	middle;
}

.padding-box {
	padding: 		10px;
}

.wrap {
	margin-bottom: 	10px;
}

.title {
	font-weight:	bold;
	font-size:		14px;
}

.middle {
	vertical-align:	middle;
}

.left {
	text-align:		left;
}

.right {
	text-align:		right;
}

.hint {
	color: 			#555555;
}

.added{
	color:			#aaaaaa;
	background-color:	#ffffff;
}

.custom-button {
	width:			auto;
	height:			auto;
	cursor:			move;
	position:		absolute;
	top:			0px;
	left:			0px;
	text-align:		center;
	font-weight: 	bold;
	font-size:		10px;
	overflow:		hidden;
}

.compositor-portrait {
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
	width:			567px;
	height:			640px;
	overflow:		hidden;
	position: 		relative;
}

.compositor-landscape {
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
	width:			640px;
	height:			413px;
	overflow:		hidden;
	position: 		relative;
}

.category-background-portrait {
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
	width:			480px;
	height:			389px;
	overflow:		hidden;
	position: 		relative;
}

.category-background-landscape {
	width:			640px;
	height:			457px;
	overflow:		hidden;
	position: 		relative;
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
}

.compositor-zoom {
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
	overflow:		hidden;
	position: 		relative;
}	

.bold {
	font-weight:	bold;
}

.loading-text {
	padding-top:	10px;
	text-align:		center;
}

.hidden {
	display:		none;
}

.application-buttons {
	padding: 		5px;
	border-left: 	none;	
	border-left: 	1px solid #d1d1d1;
	border-right: 	1px solid #d1d1d1;
	border-bottom: 	1px solid #d1d1d1;
	background-color:	#8caab5;

	background-image: -webkit-gradient(
	    linear,
    	left bottom,
    	left top,
    	color-stop(0.25, rgb(252,252,252)),
    	color-stop(0.86, rgb(236,236,236))
	);
	background-image: -moz-linear-gradient(
	    center bottom,
	    rgb(252,252,252) 25%,
	    rgb(236,236,236) 86%
	);
	
}

.dialog {
	position:		absolute;
	top:			0px;
	left:			0px;
	z-index:		201;
}

.openZoom {
	padding-top:	5xp;
	padding-left:	5px;
	cursor:			pointer;
}

.customizer-bottom-table {
	width:			100%;
	padding-top: 	5px;
	padding-left:	0px;
	padding-right:	0px;
}

.customizer-bottom-table td {
	vertical-align:	middle;
}

.reloadLayoutCustomizers {
	padding-top:	5xp;
	padding-left:	5px;
	cursor:			pointer;
}

select {
    width: 			300px;
    border: 		1px solid #8caab5;
}

promptError {
	z-index: 		350;
}

#promptLoading {
	z-index: 		300;
}

#overlay-disable {
	background-color:	#000000;
	width:			100%;
	height:			0%;
	position:		absolute;
	top:			0px;
	left:			0px;
	z-index: 		200;
}

.errorMessagesList{
    padding: 		10px;
    text-align: 	left;
	font-weight: 	bold;
	color: 			#ff0000;
	list-style-type: none;
	font-size: 		13px;
}

.removing-button{
	position: 		absolute;
	top: 			0px;
	right:			0px;
	color:			#000000;
	background-color:	#ffffff;
	z-index:		200;
	padding-top:	4px;
	text-align:		middle;
	font-size:		8px;
	width:			15px;
	height:			13px;
	cursor:			pointer;
	
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
}
.center{
	text-align:		middle;
}

.longPanel{
	width:	400px;
}
.preview {
	width:				100%;
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
	min-height:			60px;	
}
.preview-logo {
	width:				150px;
    height:             29px;
    margin:             0px auto;
	border:				1px solid #c0d7df;
	background-color:	#d5e4e9;
}
